  version: 2
  updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
        interval: 'weekly'
      assignees:
        - 'dcarbone'
      groups:
        github-actions:
          applies-to: version-updates
          patterns:
            - '*'

    - package-ecosystem: 'composer'
      directory: '/'
      schedule:
        interval: 'weekly'
      assignees:
        - 'dcarbone'

      groups:
        composer:
          applies-to: version-updates
          patterns:
            - '*'
