<?php

return <<<STRING
<?php namespace %s;

/*
 * This modified Autoloader class was generated by PHPFHIR (https://github.com/dcarbone/php-fhir).
 *
 * PHPFHIR Copyright:
 *
 * %s
 */

class PHPFHIRAutoloader
{
    const ROOT_DIR = __DIR__;

    /** @var array */
    private static \$_classMap = %s;


    /** @var bool */
    private static \$_registered = false;

    /**
     * @return bool
     * @throws \Exception
     */
    public static function register()
    {
        if (self::\$_registered)
            return self::\$_registered;
        return self::\$_registered = spl_autoload_register(array(__CLASS__, 'loadClass'), true);
    }
    /**
     * @return bool
     */
    public static function unregister()
    {
        self::\$_registered = !spl_autoload_unregister(array(__CLASS__, 'loadClass'));
        return !self::\$_registered;
    }
    /**
     * Please see associated documentation for more information on what this method looks for.
     *
     * @param string \$class
     * @return bool|null
     */
    public static function loadClass(\$class)
    {
        if (isset(self::\$_classMap[\$class]))
        {
            return (bool)require sprintf('%%s/%%s', self::ROOT_DIR, self::\$_classMap[\$class]);
        }
        return null;
    }
}
STRING;
