name: 'Load FHIR Validator'
description: 'Downloads and caches a FHIR validator jar'

inputs:
  version:
    required: false
    description: 'Version of validator to download'
    default: '6.3.4'

  base-url:
    required: false
    description: 'Base download URL'
    default: 'https://github.com/hapifhir/org.hl7.fhir.core/releases/download'

  filename:
    required: false
    description: 'Validator filename'
    default: 'validator_cli.jar'

runs:
  using: composite
  steps:
    - id: vars
      shell: bash -e {0}
      # language=sh
      run: |
        echo 'url=${{ inputs.base-url }}/${{ inputs.version }}/${{ inputs.filename }}' >> $GITHUB_OUTPUT
        echo 'cache-key=fhir-validator-${{ inputs.version }}-0' >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      id: cache
      with:
        path: '${{ github.workspace }}/bin'
        key: '${{ steps.vars.outputs.cache-key }}'

    - name: 'Download'
      if: steps.cache.outputs.cache-hit != 'true' && steps.cache.outputs.cache-hit != true
      shell: bash -e {0}
      # language=sh
      run: |
        mkdir -p '${{ github.workspace }}/bin'
        wget -q '${{ steps.vars.outputs.url }}' -O '${{ github.workspace }}/bin/${{ inputs.filename }}'